package model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

// Unit tests for TileListTest
public class TileListTest {
    RuleSetList testRuleSetList;
    MineLayout testMineLayout;
    TileList testTileList;

    @BeforeEach
    void runBefore() {
        testRuleSetList = new RuleSetList();
//        testRuleSetList.editExistingRuleSet("custom", 10, 10, 0.5, false, 10, 0.4, 0.4);
//        testMineLayout = new MineLayout(testRuleSetList.getCurrentlySelectedRuleSet());
//        testMineLayout.generateMines();
//        testMineLayout.randomizeMineLayout(26, 1111);
    }

    @Test
    void testTileList() {
        testTileList = new TileList(testRuleSetList.getCurrentlySelectedRuleSet());
        assertEquals(25, testTileList.getTileList().size());
        assertEquals(0, testTileList.getTileList().get(0).getIndex());
        assertEquals(1, testTileList.getTileList().get(1).getIndex());
        assertEquals(2, testTileList.getTileList().get(2).getIndex());
        assertEquals(3, testTileList.getTileList().get(3).getIndex());
        assertEquals(4, testTileList.getTileList().get(4).getIndex());
        assertEquals(5, testTileList.getTileList().get(5).getIndex());
        assertEquals(6, testTileList.getTileList().get(6).getIndex());
        assertEquals(7, testTileList.getTileList().get(7).getIndex());
        assertEquals(8, testTileList.getTileList().get(8).getIndex());
        assertEquals(9, testTileList.getTileList().get(9).getIndex());
        assertEquals(10, testTileList.getTileList().get(10).getIndex());
        assertEquals(11, testTileList.getTileList().get(11).getIndex());
        assertEquals(12, testTileList.getTileList().get(12).getIndex());
        assertEquals(13, testTileList.getTileList().get(13).getIndex());
        assertEquals(14, testTileList.getTileList().get(14).getIndex());
        assertEquals(15, testTileList.getTileList().get(15).getIndex());
        assertEquals(16, testTileList.getTileList().get(16).getIndex());
        assertEquals(17, testTileList.getTileList().get(17).getIndex());
        assertEquals(18, testTileList.getTileList().get(18).getIndex());
        assertEquals(19, testTileList.getTileList().get(19).getIndex());
        assertEquals(20, testTileList.getTileList().get(20).getIndex());
        assertEquals(21, testTileList.getTileList().get(21).getIndex());
        assertEquals(22, testTileList.getTileList().get(22).getIndex());
        assertEquals(23, testTileList.getTileList().get(23).getIndex());
        assertEquals(24, testTileList.getTileList().get(24).getIndex());
        assertEquals(0, testTileList.getTileList().get(0).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(1).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(2).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(3).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(4).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(5).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(6).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(7).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(8).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(9).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(10).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(11).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(12).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(13).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(14).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(15).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(16).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(17).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(18).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(19).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(20).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(21).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(22).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(23).getNumNeighbouringMines());
        assertEquals(0, testTileList.getTileList().get(24).getNumNeighbouringMines());
    }

    @Test
    void testNeighbouringMines() {
        testRuleSetList.editExistingRuleSet("custom", 10, 10, 0.1, false, 10, 0.2, 0.2);
        testMineLayout = new MineLayout(testRuleSetList.getCurrentlySelectedRuleSet());
        testTileList = new TileList(testRuleSetList.getCurrentlySelectedRuleSet());
        assertEquals(100, testTileList.getTileList().size());
        testTileList.generateTiles(testRuleSetList.getCurrentlySelectedRuleSet(), 0, 100);
        testTileList.setNeighbouringMinesAllTiles();
        List<Tile> tileList = testTileList.getTileList();
        assertEquals(0, tileList.get(0).getNumNeighbouringMines());
        assertEquals(0, tileList.get(1).getNumNeighbouringMines());
        assertEquals(0, tileList.get(2).getNumNeighbouringMines());
        assertEquals(0, tileList.get(3).getNumNeighbouringMines());
        assertEquals(0, tileList.get(4).getNumNeighbouringMines());
        assertEquals(1, tileList.get(5).getNumNeighbouringMines());
        assertEquals(1, tileList.get(6).getNumNeighbouringMines());
        assertEquals(1, tileList.get(7).getNumNeighbouringMines());
        assertEquals(0, tileList.get(8).getNumNeighbouringMines());
        assertEquals(0, tileList.get(9).getNumNeighbouringMines());
        assertEquals(0, tileList.get(10).getNumNeighbouringMines());
        assertEquals(0, tileList.get(11).getNumNeighbouringMines());
        assertEquals(0, tileList.get(12).getNumNeighbouringMines());
        assertEquals(0, tileList.get(13).getNumNeighbouringMines());
        assertEquals(0, tileList.get(14).getNumNeighbouringMines());
        assertEquals(1, tileList.get(15).getNumNeighbouringMines());
        assertEquals(0, tileList.get(16).getNumNeighbouringMines());
        assertEquals(1, tileList.get(17).getNumNeighbouringMines());
        assertEquals(0, tileList.get(18).getNumNeighbouringMines());
        assertEquals(0, tileList.get(19).getNumNeighbouringMines());
        assertEquals(0, tileList.get(20).getNumNeighbouringMines());
        assertEquals(0, tileList.get(21).getNumNeighbouringMines());
        assertEquals(0, tileList.get(22).getNumNeighbouringMines());
        assertEquals(0, tileList.get(23).getNumNeighbouringMines());
        assertEquals(0, tileList.get(24).getNumNeighbouringMines());
        assertEquals(1, tileList.get(25).getNumNeighbouringMines());
        assertEquals(1, tileList.get(26).getNumNeighbouringMines());
        assertEquals(2, tileList.get(27).getNumNeighbouringMines());
        assertEquals(2, tileList.get(28).getNumNeighbouringMines());
        assertEquals(2, tileList.get(29).getNumNeighbouringMines());
        assertEquals(0, tileList.get(30).getNumNeighbouringMines());
        assertEquals(0, tileList.get(31).getNumNeighbouringMines());
        assertEquals(0, tileList.get(32).getNumNeighbouringMines());
        assertEquals(0, tileList.get(33).getNumNeighbouringMines());
        assertEquals(0, tileList.get(34).getNumNeighbouringMines());
        assertEquals(0, tileList.get(35).getNumNeighbouringMines());
        assertEquals(0, tileList.get(36).getNumNeighbouringMines());
        assertEquals(1, tileList.get(37).getNumNeighbouringMines());
        assertEquals(1, tileList.get(38).getNumNeighbouringMines());
        assertEquals(1, tileList.get(39).getNumNeighbouringMines());
        assertEquals(1, tileList.get(40).getNumNeighbouringMines());
        assertEquals(1, tileList.get(41).getNumNeighbouringMines());
        assertEquals(1, tileList.get(42).getNumNeighbouringMines());
        assertEquals(0, tileList.get(43).getNumNeighbouringMines());
        assertEquals(0, tileList.get(44).getNumNeighbouringMines());
        assertEquals(0, tileList.get(45).getNumNeighbouringMines());
        assertEquals(0, tileList.get(46).getNumNeighbouringMines());
        assertEquals(2, tileList.get(47).getNumNeighbouringMines());
        assertEquals(3, tileList.get(48).getNumNeighbouringMines());
        assertEquals(3, tileList.get(49).getNumNeighbouringMines());
        assertEquals(1, tileList.get(50).getNumNeighbouringMines());
        assertEquals(1, tileList.get(51).getNumNeighbouringMines());
        assertEquals(2, tileList.get(52).getNumNeighbouringMines());
        assertEquals(1, tileList.get(53).getNumNeighbouringMines());
        assertEquals(0, tileList.get(54).getNumNeighbouringMines());
        assertEquals(0, tileList.get(55).getNumNeighbouringMines());
        assertEquals(0, tileList.get(56).getNumNeighbouringMines());
        assertEquals(1, tileList.get(57).getNumNeighbouringMines());
        assertEquals(0, tileList.get(58).getNumNeighbouringMines());
        assertEquals(1, tileList.get(59).getNumNeighbouringMines());
        assertEquals(2, tileList.get(60).getNumNeighbouringMines());
        assertEquals(3, tileList.get(61).getNumNeighbouringMines());
        assertEquals(2, tileList.get(62).getNumNeighbouringMines());
        assertEquals(2, tileList.get(63).getNumNeighbouringMines());
        assertEquals(1, tileList.get(64).getNumNeighbouringMines());
        assertEquals(0, tileList.get(65).getNumNeighbouringMines());
        assertEquals(0, tileList.get(66).getNumNeighbouringMines());
        assertEquals(1, tileList.get(67).getNumNeighbouringMines());
        assertEquals(1, tileList.get(68).getNumNeighbouringMines());
        assertEquals(1, tileList.get(69).getNumNeighbouringMines());
        assertEquals(0, tileList.get(70).getNumNeighbouringMines());
        assertEquals(2, tileList.get(71).getNumNeighbouringMines());
        assertEquals(2, tileList.get(72).getNumNeighbouringMines());
        assertEquals(1, tileList.get(73).getNumNeighbouringMines());
        assertEquals(1, tileList.get(74).getNumNeighbouringMines());
        assertEquals(0, tileList.get(75).getNumNeighbouringMines());
        assertEquals(0, tileList.get(76).getNumNeighbouringMines());
        assertEquals(0, tileList.get(77).getNumNeighbouringMines());
        assertEquals(0, tileList.get(78).getNumNeighbouringMines());
        assertEquals(0, tileList.get(79).getNumNeighbouringMines());
        assertEquals(1, tileList.get(80).getNumNeighbouringMines());
        assertEquals(2, tileList.get(81).getNumNeighbouringMines());
        assertEquals(2, tileList.get(82).getNumNeighbouringMines());
        assertEquals(2, tileList.get(83).getNumNeighbouringMines());
        assertEquals(1, tileList.get(84).getNumNeighbouringMines());
        assertEquals(1, tileList.get(85).getNumNeighbouringMines());
        assertEquals(1, tileList.get(86).getNumNeighbouringMines());
        assertEquals(1, tileList.get(87).getNumNeighbouringMines());
        assertEquals(0, tileList.get(88).getNumNeighbouringMines());
        assertEquals(0, tileList.get(89).getNumNeighbouringMines());
        assertEquals(0, tileList.get(90).getNumNeighbouringMines());
        assertEquals(1, tileList.get(91).getNumNeighbouringMines());
        assertEquals(0, tileList.get(92).getNumNeighbouringMines());
        assertEquals(1, tileList.get(93).getNumNeighbouringMines());
        assertEquals(0, tileList.get(94).getNumNeighbouringMines());
        assertEquals(1, tileList.get(95).getNumNeighbouringMines());
        assertEquals(0, tileList.get(96).getNumNeighbouringMines());
        assertEquals(1, tileList.get(97).getNumNeighbouringMines());
        assertEquals(0, tileList.get(98).getNumNeighbouringMines());
        assertEquals(0, tileList.get(99).getNumNeighbouringMines());
    }

    @Test
    void testMoreNeighbouringMines() {
        testRuleSetList.editExistingRuleSet("custom", 10, 10, 0.5, false, 10, 0.25, 0.25);
        testMineLayout = new MineLayout(testRuleSetList.getCurrentlySelectedRuleSet());
        testTileList = new TileList(testRuleSetList.getCurrentlySelectedRuleSet());
        assertEquals(100, testTileList.getTileList().size());
        testTileList.generateTiles(testRuleSetList.getCurrentlySelectedRuleSet(), 15, 100);
        testTileList.setNeighbouringMinesAllTiles();
        List<Tile> tileList = testTileList.getTileList();
        assertEquals(0, tileList.get(0).getNumNeighbouringMines());
        assertEquals(2, tileList.get(1).getNumNeighbouringMines());
        assertEquals(1, tileList.get(2).getNumNeighbouringMines());
        assertEquals(2, tileList.get(3).getNumNeighbouringMines());
        assertEquals(1, tileList.get(4).getNumNeighbouringMines());
        assertEquals(2, tileList.get(5).getNumNeighbouringMines());
        assertEquals(2, tileList.get(6).getNumNeighbouringMines());
        assertEquals(1, tileList.get(7).getNumNeighbouringMines());
        assertEquals(2, tileList.get(8).getNumNeighbouringMines());
        assertEquals(1, tileList.get(9).getNumNeighbouringMines());
        assertEquals(2, tileList.get(10).getNumNeighbouringMines());
        assertEquals(3, tileList.get(11).getNumNeighbouringMines());
        assertEquals(2, tileList.get(12).getNumNeighbouringMines());
        assertEquals(4, tileList.get(13).getNumNeighbouringMines());
        assertEquals(4, tileList.get(14).getNumNeighbouringMines());
        assertEquals(4, tileList.get(15).getNumNeighbouringMines());
        assertEquals(2, tileList.get(16).getNumNeighbouringMines());
        assertEquals(2, tileList.get(17).getNumNeighbouringMines());
        assertEquals(2, tileList.get(18).getNumNeighbouringMines());
        assertEquals(0, tileList.get(19).getNumNeighbouringMines());
        assertEquals(1, tileList.get(20).getNumNeighbouringMines());
        assertEquals(3, tileList.get(21).getNumNeighbouringMines());
        assertEquals(1, tileList.get(22).getNumNeighbouringMines());
        assertEquals(3, tileList.get(23).getNumNeighbouringMines());
        assertEquals(3, tileList.get(24).getNumNeighbouringMines());
        assertEquals(5, tileList.get(25).getNumNeighbouringMines());
        assertEquals(5, tileList.get(26).getNumNeighbouringMines());
        assertEquals(4, tileList.get(27).getNumNeighbouringMines());
        assertEquals(4, tileList.get(28).getNumNeighbouringMines());
        assertEquals(3, tileList.get(29).getNumNeighbouringMines());
        assertEquals(2, tileList.get(30).getNumNeighbouringMines());
        assertEquals(4, tileList.get(31).getNumNeighbouringMines());
        assertEquals(2, tileList.get(32).getNumNeighbouringMines());
        assertEquals(4, tileList.get(33).getNumNeighbouringMines());
        assertEquals(4, tileList.get(34).getNumNeighbouringMines());
        assertEquals(4, tileList.get(35).getNumNeighbouringMines());
        assertEquals(3, tileList.get(36).getNumNeighbouringMines());
        assertEquals(2, tileList.get(37).getNumNeighbouringMines());
        assertEquals(2, tileList.get(38).getNumNeighbouringMines());
        assertEquals(1, tileList.get(39).getNumNeighbouringMines());
        assertEquals(4, tileList.get(40).getNumNeighbouringMines());
        assertEquals(5, tileList.get(41).getNumNeighbouringMines());
        assertEquals(5, tileList.get(42).getNumNeighbouringMines());
        assertEquals(4, tileList.get(43).getNumNeighbouringMines());
        assertEquals(5, tileList.get(44).getNumNeighbouringMines());
        assertEquals(5, tileList.get(45).getNumNeighbouringMines());
        assertEquals(5, tileList.get(46).getNumNeighbouringMines());
        assertEquals(5, tileList.get(47).getNumNeighbouringMines());
        assertEquals(5, tileList.get(48).getNumNeighbouringMines());
        assertEquals(3, tileList.get(49).getNumNeighbouringMines());
        assertEquals(3, tileList.get(50).getNumNeighbouringMines());
        assertEquals(5, tileList.get(51).getNumNeighbouringMines());
        assertEquals(5, tileList.get(52).getNumNeighbouringMines());
        assertEquals(5, tileList.get(53).getNumNeighbouringMines());
        assertEquals(4, tileList.get(54).getNumNeighbouringMines());
        assertEquals(3, tileList.get(55).getNumNeighbouringMines());
        assertEquals(3, tileList.get(56).getNumNeighbouringMines());
        assertEquals(1, tileList.get(57).getNumNeighbouringMines());
        assertEquals(2, tileList.get(58).getNumNeighbouringMines());
        assertEquals(2, tileList.get(59).getNumNeighbouringMines());
        assertEquals(4, tileList.get(60).getNumNeighbouringMines());
        assertEquals(6, tileList.get(61).getNumNeighbouringMines());
        assertEquals(5, tileList.get(62).getNumNeighbouringMines());
        assertEquals(7, tileList.get(63).getNumNeighbouringMines());
        assertEquals(6, tileList.get(64).getNumNeighbouringMines());
        assertEquals(6, tileList.get(65).getNumNeighbouringMines());
        assertEquals(5, tileList.get(66).getNumNeighbouringMines());
        assertEquals(4, tileList.get(67).getNumNeighbouringMines());
        assertEquals(4, tileList.get(68).getNumNeighbouringMines());
        assertEquals(2, tileList.get(69).getNumNeighbouringMines());
        assertEquals(3, tileList.get(70).getNumNeighbouringMines());
        assertEquals(7, tileList.get(71).getNumNeighbouringMines());
        assertEquals(5, tileList.get(72).getNumNeighbouringMines());
        assertEquals(6, tileList.get(73).getNumNeighbouringMines());
        assertEquals(6, tileList.get(74).getNumNeighbouringMines());
        assertEquals(6, tileList.get(75).getNumNeighbouringMines());
        assertEquals(4, tileList.get(76).getNumNeighbouringMines());
        assertEquals(3, tileList.get(77).getNumNeighbouringMines());
        assertEquals(2, tileList.get(78).getNumNeighbouringMines());
        assertEquals(2, tileList.get(79).getNumNeighbouringMines());
        assertEquals(2, tileList.get(80).getNumNeighbouringMines());
        assertEquals(5, tileList.get(81).getNumNeighbouringMines());
        assertEquals(4, tileList.get(82).getNumNeighbouringMines());
        assertEquals(6, tileList.get(83).getNumNeighbouringMines());
        assertEquals(4, tileList.get(84).getNumNeighbouringMines());
        assertEquals(5, tileList.get(85).getNumNeighbouringMines());
        assertEquals(6, tileList.get(86).getNumNeighbouringMines());
        assertEquals(5, tileList.get(87).getNumNeighbouringMines());
        assertEquals(5, tileList.get(88).getNumNeighbouringMines());
        assertEquals(3, tileList.get(89).getNumNeighbouringMines());
        assertEquals(2, tileList.get(90).getNumNeighbouringMines());
        assertEquals(4, tileList.get(91).getNumNeighbouringMines());
        assertEquals(2, tileList.get(92).getNumNeighbouringMines());
        assertEquals(3, tileList.get(93).getNumNeighbouringMines());
        assertEquals(2, tileList.get(94).getNumNeighbouringMines());
        assertEquals(3, tileList.get(95).getNumNeighbouringMines());
        assertEquals(3, tileList.get(96).getNumNeighbouringMines());
        assertEquals(3, tileList.get(97).getNumNeighbouringMines());
        assertEquals(3, tileList.get(98).getNumNeighbouringMines());
        assertEquals(1, tileList.get(99).getNumNeighbouringMines());
    }

    @Test
    void testEvenMoreNeighbouringMines() {
        testRuleSetList.editExistingRuleSet("custom", 5, 5, 0.5, false, 10, 0.25, 0.25);
        testMineLayout = new MineLayout(testRuleSetList.getCurrentlySelectedRuleSet());
        testTileList = new TileList(testRuleSetList.getCurrentlySelectedRuleSet());
        assertEquals(25, testTileList.getTileList().size());
        testTileList.generateTiles(testRuleSetList.getCurrentlySelectedRuleSet(), 12, 888);
        testTileList.setNeighbouringMinesAllTiles();
        List<Tile> tileList = testTileList.getTileList();
        assertEquals(1, tileList.get(0).getNumNeighbouringMines());
        assertEquals(2, tileList.get(1).getNumNeighbouringMines());
        assertEquals(1, tileList.get(2).getNumNeighbouringMines());
        assertEquals(3, tileList.get(3).getNumNeighbouringMines());
        assertEquals(2, tileList.get(4).getNumNeighbouringMines());
        assertEquals(2, tileList.get(5).getNumNeighbouringMines());
        assertEquals(4, tileList.get(6).getNumNeighbouringMines());
        assertEquals(3, tileList.get(7).getNumNeighbouringMines());
        assertEquals(4, tileList.get(8).getNumNeighbouringMines());
        assertEquals(2, tileList.get(9).getNumNeighbouringMines());
        assertEquals(2, tileList.get(10).getNumNeighbouringMines());
        assertEquals(3, tileList.get(11).getNumNeighbouringMines());
        assertEquals(3, tileList.get(12).getNumNeighbouringMines());
        assertEquals(4, tileList.get(13).getNumNeighbouringMines());
        assertEquals(3, tileList.get(14).getNumNeighbouringMines());
        assertEquals(4, tileList.get(15).getNumNeighbouringMines());
        assertEquals(5, tileList.get(16).getNumNeighbouringMines());
        assertEquals(3, tileList.get(17).getNumNeighbouringMines());
        assertEquals(2, tileList.get(18).getNumNeighbouringMines());
        assertEquals(1, tileList.get(19).getNumNeighbouringMines());
        assertEquals(1, tileList.get(20).getNumNeighbouringMines());
        assertEquals(2, tileList.get(21).getNumNeighbouringMines());
        assertEquals(3, tileList.get(22).getNumNeighbouringMines());
        assertEquals(3, tileList.get(23).getNumNeighbouringMines());
        assertEquals(2, tileList.get(24).getNumNeighbouringMines());
    }

    @Test
    void testYetMoreNeighbouringMines() {
        testRuleSetList.editExistingRuleSet("custom", 5, 5, 0.5, false, 10, 0.25, 0.25);
        testMineLayout = new MineLayout(testRuleSetList.getCurrentlySelectedRuleSet());
        testTileList = new TileList(testRuleSetList.getCurrentlySelectedRuleSet());
        assertEquals(25, testTileList.getTileList().size());
        testTileList.generateTiles(testRuleSetList.getCurrentlySelectedRuleSet(), 12, 99);
        testTileList.setNeighbouringMinesAllTiles();
        List<Tile> tileList = testTileList.getTileList();
        assertEquals(3, tileList.get(0).getNumNeighbouringMines());
        assertEquals(3, tileList.get(1).getNumNeighbouringMines());
        assertEquals(3, tileList.get(2).getNumNeighbouringMines());
        assertEquals(3, tileList.get(3).getNumNeighbouringMines());
        assertEquals(2, tileList.get(4).getNumNeighbouringMines());
        assertEquals(3, tileList.get(5).getNumNeighbouringMines());
        assertEquals(4, tileList.get(6).getNumNeighbouringMines());
        assertEquals(5, tileList.get(7).getNumNeighbouringMines());
        assertEquals(2, tileList.get(8).getNumNeighbouringMines());
        assertEquals(1, tileList.get(9).getNumNeighbouringMines());
        assertEquals(5, tileList.get(10).getNumNeighbouringMines());
        assertEquals(5, tileList.get(11).getNumNeighbouringMines());
        assertEquals(5, tileList.get(12).getNumNeighbouringMines());
        assertEquals(4, tileList.get(13).getNumNeighbouringMines());
        assertEquals(3, tileList.get(14).getNumNeighbouringMines());
        assertEquals(2, tileList.get(15).getNumNeighbouringMines());
        assertEquals(4, tileList.get(16).getNumNeighbouringMines());
        assertEquals(3, tileList.get(17).getNumNeighbouringMines());
        assertEquals(3, tileList.get(18).getNumNeighbouringMines());
        assertEquals(0, tileList.get(19).getNumNeighbouringMines());
        assertEquals(2, tileList.get(20).getNumNeighbouringMines());
        assertEquals(4, tileList.get(21).getNumNeighbouringMines());
        assertEquals(2, tileList.get(22).getNumNeighbouringMines());
        assertEquals(3, tileList.get(23).getNumNeighbouringMines());
        assertEquals(1, tileList.get(24).getNumNeighbouringMines());
    }
}

